### ISSUE TITLE
Can snpnet be used on bed files directly?

### ISSUE THREAD

**Issue by privefl** [junyangq/snpnet#34]
I think the preprint says that snpnet can be used on bed files directly.
However, the documentation seems to talk only about pgen files.

Could you please clarify this point?

**Comment by junyangq** [comment]
Hi @privefl thanks for raising this point. In the [latest version](https://doi.org/10.1101/2020.01.20.913194) of the manuscript, we assume pgen files, to be consistent with the latest version of the package. To use bed files, one may need to use an earlier version of the package as in [branch V1.0](https://github.com/junyangq/snpnet/tree/V1.0).

**Comment by privefl** [comment]
Thanks for your reply.
In the latest version of the manuscript, you still talk about doing some optimized matrix computations because you have only 0s, 1s, 2s and NAs.
Are you still using this when using pgen files? Do you handle dosage data?

**Comment by privefl** [comment]
Moreover, you still talk about 
> Moreover,  the existing convenient data interface provided by the BEDMatrix package further facilitates our implementation.

whereas BEDMatrix does not handle pgen format yet, but only bed format for now, if I'm not mistaken.

**Comment by junyangq** [comment]
Good catches. I take back the previous reply and sorry for the confusion. In fact the description and results in the paper should be all about the earlier version of the package https://github.com/junyangq/snpnet/tree/V1.0. We will correct the pgen assumption in the paper and add discussion about major changes and further optimizations made for the latest implementation.

**Comment by junyangq** [comment]
Thank you @privefl for pointing out this issue!

**Comment by privefl** [comment]
Could I ask how far is it from being published?

**Comment by junyangq** [comment]
It's under review after a major revision.
