### ISSUE TITLE
Both FID and IID should be used for identifier for individuals

### ISSUE THREAD

**Issue by yk-tanigawa** [junyangq/snpnet#6]
Hi Junyang,

As we talked last time, I strongly recommend you to use both FID and IID as the identifier for individuals.
https://github.com/junyangq/snpnet/blob/4b0687cbe092ba1936f16f1b2059532b57faa5b4/R/snpnet.R#L75

I think you can mimic the behavior of BEDMatrix::BEDMatrix(), meaning that you may concatenate the two IDs with an underscore, like `FID_IID`.
https://github.com/junyangq/snpnet/blob/4b0687cbe092ba1936f16f1b2059532b57faa5b4/R/snpnet.R#L81

Also, I would recommend changing the separator in `.phe` file. I think the current package assume it is a 'csv' file, but the default behavior of PLINK bed/bim/fam file is a tab-separated file.

**Comment by junyangq** [comment]
This has been resolved. Thanks for the suggestion @yk-tanigawa
